SELECT
  DATE_ADD(hiredate, INTERVAL -5 DAY) AS HD_MINUS_5D,
  DATE_ADD(hiredate, INTERVAL 5 DAY) AS HD_PLUS_5D,
  DATE_ADD(hiredate, INTERVAL -5 MONTH) AS HD_MINUS_5M,
  DATE_ADD(hiredate, INTERVAL 5 MONTH) AS HD_PLUS_5M,
  DATE_ADD(hiredate, INTERVAL -5 YEAR) AS HD_MINUS_5Y,
  DATE_ADD(hiredate, INTERVAL 5 YEAR) AS HD_PLUS_5Y,
FROM
  sql_cookbook.emp
